### ISSUE TITLE
submitted but unpublished records aren't making it to the repo

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-metadata-entry-form-files#2] opened 2024-07-22 14:15 UTC
I'm not sure if that is the expected behaviour, I thought no. Looks like the submitted records aren't making it the repo.

It would be helpful to have them made available to facilitate the workflow with ERDDAP. Though it this is not ideal with the CKAN workflow then we can omit it for now. 

Another solution would perhaps be the store those files in a submitted subdirectory which is omitted by ckan

Example record: https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/7U7b8oPpeTN6gjvXlUCTGJr5pga2/-O25qzW3OpioeACGpRHl

**Comment by fostermh** [comment] 2024-07-22 20:20
there was a path issue when pushing records to the `unpublished` folder. which is now fixed.

**Comment by JessyBarrette** [comment] 2024-07-22 20:26
Awesome thanks!

*Jessy Barrette M.Sc.*
*Marine Data and Instrumentation Specialist*
Hakai Institute <https://www.hakai.org/> | CIOOS Pacific
<https://cioospacific.ca/> | CIOOS <https://cioos.ca/> |
***@***.*** | (C) (418) 999-5745


Le lun. 22 juill. 2024 à 16:21, Matthew Foster ***@***.***> a
écrit :

**Comment by fostermh** [comment] 2024-07-22 20:39
duplicate of https://github.com/HakaiInstitute/hakai-metadata-entry-form-files/issues/1

**Closed** 2024-07-24 14:21 UTC
